//echo 'hello from another_scenario-test dir'
//
////dir = new File(__FILE__).parentFile.absoluteFile
//
////echo "the dir is: ${dir}"
//
//def pipeline = node {
//    git url: 'git://10.32.128.152/gatling-puppet-load-test',
//            branch: 'scratch/master/pipeline-test'
//    load 'jenkins-integration/jenkins-jobs/common/scripts/hello.groovy'
//}
//
//pipeline.sayHello()
//
//echo "ENVIRONMENT IS: ${env.keys}"

