node {
    checkout scm

    println "CLASSLOADER URLS: " + this.class.classLoader.getURLs()

    pipeline = load 'jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy'
}

pipeline.single_pipeline([
        job_name: 'singletest',
        code_deploy: [
                type: pipeline.CodeDeployType.R10K,



        ]
])
