- job-template:
    name: 'run-{name}-gatling-scenario'
    parameters:
    - string:
        name: PUPPET_GATLING_SIMULATION_CONFIG
        description: "The gatling scenario file to run"
        default: "../simulation-runner/config/scenarios/ops-scenario.json"
    - string:
        name: PUPPET_GATLING_SIMULATION_ID
        description: "A descriptive identifier for this run"
        default: "OPS-CatalogZero"
    - string:
        name: PUPPET_GATLING_MASTER_BASE_URL
        description: "The URL of the puppet master SUT"

    scm:
      - git:
          url: https://github.com/puppetlabs/gatling-puppet-load-test.git
          branches:
              - master
          browser: githubweb
          browser-url: http://github.com/puppetlabs/gatling-puppet-load-test

    builders:
#      - shell:
#              "pushd jenkins-integration && \
#              ./jenkins-jobs/ops-deployment/setup_master.sh && \
#              ./jenkins-jobs/ops-deployment/run_simulation.sh && \
#              popd"
      - shell:
          "pushd jenkins-integration && \
          ./jenkins-jobs/ops-deployment/run_simulation.sh && \
          popd"
#      - sbt:
#          actions: "run"
#          subdir-path: "./simulation-runner"

- project:
    name: ops-deployment
    jobs:
      - "run-{name}-gatling-scenario"
